[project]
name = "rag-embedder"
version = "0.1.0"
description = "Handles text to vector embedding using OpenAI"
readme = "README.md"
authors = [
    { name = "sigridjineth", email = "sigrid.jinhyung@gmail.com" }
]
requires-python = ">=3.11"
dependencies = [
    "rag-core",
    "openai>=1.0.0",
    "numpy"
]

[project.optional-dependencies]
test = ["pytest>=7.0.0", "pytest-asyncio>=0.21.0"]

[tool.uv.sources]
rag-core = { workspace = true }

[build-system]
requires = ["uv_build>=0.0.2,<1.0.0"]
build-backend = "uv_build"