[project]
name = "storm-client"
version = "0.1.0"
description = "HTTP client for Storm Parse API"
readme = "README.md"
authors = [
    { name = "sigridjineth", email = "sigrid.jinhyung@gmail.com" }
]
requires-python = ">=3.11"
dependencies = ["rag-core", "httpx>=0.27.0"]

[project.optional-dependencies]
test = ["pytest>=7.0.0", "pytest-asyncio>=0.21.0", "pytest-httpx>=0.30.0"]

[tool.uv.sources]
rag-core = { workspace = true }

[build-system]
requires = ["uv_build>=0.0.2,<1.0.0"]
build-backend = "uv_build"
