[project]
name = "rag-api"
version = "0.1.0"
description = "FastAPI endpoints for RAG pipeline"
readme = "README.md"
authors = [
    { name = "sigridjineth", email = "sigrid.jinhyung@gmail.com" }
]
requires-python = ">=3.11"
dependencies = ["rag-core", "rag-service", "fastapi>=0.115.0", "uvicorn[standard]>=0.25.0", "python-multipart>=0.0.6"]

[project.optional-dependencies]
test = ["pytest>=7.0.0", "pytest-asyncio>=0.21.0", "httpx>=0.27.0"]

[tool.uv.sources]
rag-core = { workspace = true }
rag-service = { workspace = true }

[build-system]
requires = ["uv_build>=0.0.2,<1.0.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "pytest-mock>=3.14.1",
]
